name: 'Dart Analyze'
description: 'Analyze a dart code'
author: 'Valentin Vignal'
branding:
  icon: 'check-circle'
  color: 'gray-dark'
inputs:
  fail-on:
    description: 'When the action will fail. Optional. Option: `error`, `warning`, `info`, `format`, `nothing`. Default: `error`.'
    default: 'error'
    required: false
  working-directory:
    description: 'The working directory. Optional. Default: `./`.'
    default: ./
    required: false
  token:
    description: 'The github token.'
    required: false
    default: ${{ github.token }}
  check-renamed-files:
    description: 'Whether it should check the renamed files with no changes. Options: `false`, `true`. Default: `false`.'
    required: false
    default: 'false'
  emojis:
    description: 'Whether it should include emojis in the comment. Option: `false`, `true`. Default: `true`.'
    required: false
    default: 'true'
  format:
    description: 'Whether it should check the formatting. Options: `true`, `false`. Default: `true`.'
    required: false
    default: 'true'
  line-length:
    description: 'The line length for that dart format command. Default: default value for `flutter format`.'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
